-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfX2kfoRh+zJ6eJwO
235znfLHexjviqQg+iKSn/NlVW6gCgYIKoZIzj0DAQehRANCAAThI2xINCBDb06h
ZMokkMoPiOUC0cr0gvAKknOPbximlv0MXc8Ra+ANPDZ2xWvHxUOBNUiPylfZzdBa
Jb+hmHY+
-----END PRIVATE KEY-----